[package]
name = "msw"
version = "0.1.0"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "gzip", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tui = "0.9"
